In [3]:
import numpy as np
import matplotlib.pylab as plt

In [4]:
def function_2(x):
    return x[0]**2 + x[1]**2

In [5]:
def numerical_gradient(f, x):
    h = 1e-4    #0.0001
    grad = np.zeros_like(x)     # x와 형상이 같은 배열을 생성

    for idx in range(x.size):
        tmp_val = x[idx]
        # f(x+h) 계산
        x[idx] = tmp_val + h
        fxh1 = f(x)

        # f(x-h) 계산
        x[idx] = tmp_val - h
        fxh2 = f(x)

        grad[idx] = (fxh1 - fxh2) / (2 * h)
        x[idx] = tmp_val  # 값 복원
    return grad

In [6]:
numerical_gradient(function_2, np.array([3.0, 4.0]))

array([6., 8.])

In [7]:
numerical_gradient(function_2, np.array([0.0, 2.0]))

array([0., 4.])

In [8]:
numerical_gradient(function_2, np.array([3.0, 0.0]))

array([6., 0.])

In [9]:
def gradient_descent(f, init_x, lr=0.01, step_num=100):
    x = init_x

    for i in range(step_num):
        grad = numerical_gradient(f, x)
        x -= lr * grad
    return x

In [10]:
def function_2(x):
    return x[0]**2 + x[1]**2

init_x = np.array([-3.0, 4.0])
gradient_descent(function_2, init_x=init_x, lr=0.1, step_num=100)

array([-6.11110793e-10,  8.14814391e-10])

In [11]:
# 학습률이 너무 큰 예 : lr = 10.0
gradient_descent(function_2, init_x=init_x, lr=10.0, step_num=100)

array([ 2.34235971e+12, -3.96091057e+12])

In [12]:
# 학습률이 너무 작은 예 : lr = 1e-10
gradient_descent(function_2, init_x=init_x, lr=1e-10, step_num=100)

array([ 2.34235971e+12, -3.96091057e+12])

In [19]:
# coding: utf-8
import sys, os
sys.path.append(os.pardir)  # 부모 디렉터리의 파일을 가져올 수 있도록 설정
sys.path.append(os.getcwd())

import numpy as np
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient


class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2,3) # 정규분포로 초기화

    def predict(self, x):
        return np.dot(x, self.W)

    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss

In [14]:
net = simpleNet()
print(net.W)  # 가중치 매개변수

[[-1.44573146 -2.66376281  1.57585935]
 [ 0.48526365 -0.12530544  0.75211838]]


In [15]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)

[-0.43070159 -1.71103258  1.62242215]


In [18]:
np.argmax(p) # 최댓값의 인덱스

2

In [17]:
t = np.array([0,0,1]) # 정답 레이블
net.loss(x, t)

0.1518648615661902

In [20]:
# 기울기
def f(W):
    return net.loss(x, t)

dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.06615105  0.01838637 -0.08453743]
 [ 0.09922658  0.02757956 -0.12680614]]
